name: Find Pull Requests
author: Cicatrice
description: Find all open PRs associated with the current commit. Based on jwalton/gh-find-current-pr.
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client.  Defaults to github provided token.
    default: ${{ github.token }}
  sha:
    description: Sha to get PR for.  Defaults to current sha.
    default: ${{ github.sha }}
outputs:
  prs:
    description: The PRs if any was found. (e.g. ['123','456'] ; [] if none)
runs:
  using: node12
  main: 'main.js'
branding:
  icon: git-pull-request
  color: blue
